/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProvisioningRouteRouteImport } from './routes/provisioning/route'
import { Route as ProvisioningIndexRouteImport } from './routes/provisioning/index'
import { Route as ProvisioningSettingsRouteImport } from './routes/provisioning/settings'
import { Route as ProvisioningInstallRouteImport } from './routes/provisioning/install'
import { Route as ProvisioningAuthRouteImport } from './routes/provisioning/auth'

const ProvisioningRouteRoute = ProvisioningRouteRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisioningIndexRoute = ProvisioningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvisioningRouteRoute,
} as any)
const ProvisioningSettingsRoute = ProvisioningSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProvisioningRouteRoute,
} as any)
const ProvisioningInstallRoute = ProvisioningInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ProvisioningRouteRoute,
} as any)
const ProvisioningAuthRoute = ProvisioningAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ProvisioningRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/provisioning': typeof ProvisioningRouteRouteWithChildren
  '/provisioning/auth': typeof ProvisioningAuthRoute
  '/provisioning/install': typeof ProvisioningInstallRoute
  '/provisioning/settings': typeof ProvisioningSettingsRoute
  '/provisioning/': typeof ProvisioningIndexRoute
}
export interface FileRoutesByTo {
  '/provisioning/auth': typeof ProvisioningAuthRoute
  '/provisioning/install': typeof ProvisioningInstallRoute
  '/provisioning/settings': typeof ProvisioningSettingsRoute
  '/provisioning': typeof ProvisioningIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/provisioning': typeof ProvisioningRouteRouteWithChildren
  '/provisioning/auth': typeof ProvisioningAuthRoute
  '/provisioning/install': typeof ProvisioningInstallRoute
  '/provisioning/settings': typeof ProvisioningSettingsRoute
  '/provisioning/': typeof ProvisioningIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/provisioning'
    | '/provisioning/auth'
    | '/provisioning/install'
    | '/provisioning/settings'
    | '/provisioning/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/provisioning/auth'
    | '/provisioning/install'
    | '/provisioning/settings'
    | '/provisioning'
  id:
    | '__root__'
    | '/provisioning'
    | '/provisioning/auth'
    | '/provisioning/install'
    | '/provisioning/settings'
    | '/provisioning/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProvisioningRouteRoute: typeof ProvisioningRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provisioning': {
      id: '/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof ProvisioningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisioning/': {
      id: '/provisioning/'
      path: '/'
      fullPath: '/provisioning/'
      preLoaderRoute: typeof ProvisioningIndexRouteImport
      parentRoute: typeof ProvisioningRouteRoute
    }
    '/provisioning/settings': {
      id: '/provisioning/settings'
      path: '/settings'
      fullPath: '/provisioning/settings'
      preLoaderRoute: typeof ProvisioningSettingsRouteImport
      parentRoute: typeof ProvisioningRouteRoute
    }
    '/provisioning/install': {
      id: '/provisioning/install'
      path: '/install'
      fullPath: '/provisioning/install'
      preLoaderRoute: typeof ProvisioningInstallRouteImport
      parentRoute: typeof ProvisioningRouteRoute
    }
    '/provisioning/auth': {
      id: '/provisioning/auth'
      path: '/auth'
      fullPath: '/provisioning/auth'
      preLoaderRoute: typeof ProvisioningAuthRouteImport
      parentRoute: typeof ProvisioningRouteRoute
    }
  }
}

interface ProvisioningRouteRouteChildren {
  ProvisioningAuthRoute: typeof ProvisioningAuthRoute
  ProvisioningInstallRoute: typeof ProvisioningInstallRoute
  ProvisioningSettingsRoute: typeof ProvisioningSettingsRoute
  ProvisioningIndexRoute: typeof ProvisioningIndexRoute
}

const ProvisioningRouteRouteChildren: ProvisioningRouteRouteChildren = {
  ProvisioningAuthRoute: ProvisioningAuthRoute,
  ProvisioningInstallRoute: ProvisioningInstallRoute,
  ProvisioningSettingsRoute: ProvisioningSettingsRoute,
  ProvisioningIndexRoute: ProvisioningIndexRoute,
}

const ProvisioningRouteRouteWithChildren =
  ProvisioningRouteRoute._addFileChildren(ProvisioningRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProvisioningRouteRoute: ProvisioningRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
